# Generated by Django 3.0.2 on 2020-01-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='temasFavoritos',
            field=models.ManyToManyField(null=True, related_name='TemaFavoritoUsuario', to='main.Tema'),
        ),
    ]
