# Generated by Django 3.0.2 on 2020-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200116_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='ultimaRespuesta',
            field=models.DateField(null=True),
        ),
    ]
