# Generated by Django 3.0.2 on 2020-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200116_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='ultimaRespuesta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
