# Generated by Django 3.0.2 on 2020-01-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArtista', models.IntegerField()),
                ('nombre', models.TextField()),
                ('url', models.URLField()),
                ('pictureURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('idTag', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tagValue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.Artista')),
                ('idTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('tiempoEscucha', models.BigIntegerField()),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacion.Artista')),
            ],
        ),
    ]
