# Generated by Django 3.0.2 on 2020-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0002_auto_20200107_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='idTag',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
