# Generated by Django 3.0.2 on 2020-01-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('generos', models.TextField()),
                ('formatoEmision', models.TextField()),
                ('numEpisodios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.BigIntegerField()),
                ('puntuacion', models.IntegerField()),
                ('animeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resSysC.Anime')),
            ],
        ),
    ]
