# Generated by Django 2.0 on 2019-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191128_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('precio', models.IntegerField()),
                ('lenguages', models.TextField()),
                ('municipio', models.TextField()),
                ('codigo', models.IntegerField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuaciones',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idPelicula',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ocupacion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
